js {
    const {
        source: source_config
    } = require("definitions/param/source/ehr_bed.js");
    const {
        fn_calculateConcat,
        fn_calculateHash
    } = require("includes/functions.js");
}

config {
    type: "table",
    name: "step_tbl_process_bed_dim",
    schema: dataform.projectConfig.vars.stagingDataset,
    dependencies: ["step_tbl_read_bed_dim"],
    description: "Applies business logic to bed dimension",
    tags: ["bed", "conformed", "dim"]
}


WITH
    cte_read_data AS (

        SELECT
            *
        FROM
            ${ref("step_tbl_read_bed_dim")}
    ),

    cte_transformed AS (

        SELECT
            bed_id,
            TRIM(bed_category) AS bed_category,
            ${source_config.get_status_flag('ac_status')} AS ac_status,
            CAST(sharing_capacity AS INT64) AS sharing_capacity,
            TRIM(operational_status) AS operational_status,
            TRIM(room_no) AS room_number,
            CAST(floor_no AS INT64) AS floor_number,

            CURRENT_TIMESTAMP AS load_ts

        FROM
            cte_read_data
    ),

    cte_final AS (

        SELECT
            ${fn_calculateHash(source_config.dk)} AS bed_dk,
            ${fn_calculateConcat(source_config.bk)} AS bed_bk,
            ${fn_calculateHash(source_config.hashdiff)} AS hashdiff,

            CURRENT_TIMESTAMP() AS vld_fm_ts,
            TIMESTAMP '9999-12-31 23:59:59+00' AS vld_to_ts,
            'Y' as current_ind,

            bed_id,
            bed_category,
            ac_status,
            sharing_capacity,
            operational_status,
            room_number,
            floor_number,
            load_ts

        FROM
            cte_transformed
    )

SELECT * FROM cte_final;
