js {
    const {
        fn_SCD2load
    } = require("includes/functions.js");

    const { projectConfig, datasets } = require("includes/glb_env.js");

    const { source } = require("definitions/param/source/ehr_bed.js");
    const { target } = require("definitions/param/target/bed_dim.js");
}

config {
    type: "operations",
    hasOutput: true,
    name: "step_tbl_write_bed_dim",
    schema: dataform.projectConfig.vars.stagingDataset,
    dependencies: ["step_tbl_process_bed_dim"],
    description: "Loads processed data into the final bed dimension table.",
    tags: ["bed", "conformed", "dim"]
}


${fn_SCD2load({
    source_ref: ref("step_tbl_process_bed_dim"),
    target_name: `${target.target_table}`,
    project_id: projectConfig.projectName,
    tgt_dataset: datasets.target,
    hash_column: target.hash_column,
    natural_key: target.bk,
    target_params: target
})}
