js {
    const {
        target_c: target
    } = require("definitions/param/target/order_type_dim.js");
    const {
        source: source,
    } = require("definitions/param/source/ehr_clinical_ref_data.js");

    let{
     dv_env_vars,
     fn_calculateHash,
     fn_calculateConcat,  
    }=require("includes/functions.js")
}

config {
    type: "table",
    name: "step_tbl_process_order_type_dim",
    schema: glb_env.datasets.staging,
    dependencies: ["step_tbl_read_order_type_dim"],
    description: "Applies business logic to the order type data.",
    tags: ["orders", "dim"]
}

WITH cte_read_data AS (
        SELECT 
            ref_code,
            ref_name,
            order_category,
            order_sub_category,
            typical_turnaround_mins
        FROM ${ref("step_tbl_read_order_type_dim")}
    ),
    cte_transform AS (
        SELECT
            ${fn_calculateHash(source.dk)} AS ord_type_dk,
            ${fn_calculateConcat(source.bk)} AS ord_type_bk,
            trim(ref_name) as ord_name,
            trim(order_category) as ord_cat,
            trim(order_sub_category) as ord_sub_cat,
            typical_turnaround_mins as turnaround_mins,
        FROM
            cte_read_data
    ),
    cte_final AS (
        SELECT
            ord_type_dk,
            ord_type_bk,
            ${fn_calculateHash(source.hash_diff_1)} AS hash_diff,
            ord_name,
            ord_cat,
            ord_sub_cat,
            turnaround_mins,
            current_timestamp() as load_ts
        FROM
            cte_transform
    )

select
 ord_type_dk,
 ord_type_bk,
 hash_diff,
 ord_name,
 ord_cat,
 ord_sub_cat,
 turnaround_mins,
 load_ts
from cte_final

