js {
    const {
        fn_factLoad
    } = require("includes/functions.js");
    const { projectConfig, datasets } = require("includes/glb_env.js");
    const { target } = require("definitions/param/target/bed_census_daily_fct.js");
}

config {
    type: "operations",
    hasOutput: true,
    name: "step_tbl_write_bed_census_daily_fct",
    schema: dataform.projectConfig.vars.stagingDataset,
    dependencies: ["step_tbl_process_bed_census_daily_fct"],
    description: "Loads processed bed census daily fact data into the target table.",
    tags: ["bed", "fact", "census"]
}

${fn_factLoad({
    source_ref: ref("step_tbl_process_bed_census_daily_fct"),
    target_name: `${target.target_table}`,
    project_id: projectConfig.projectName,
    tgt_dataset: datasets.target,
    natural_key: "bed_census_bk",
    target_params: target
})}
