js {
    const { projectConfig, datasets } = require("includes/glb_env.js");
    const { fn_SCD2load } = require("includes/functions.js");
    const { target } = require("definitions/param/target/risk_score_fct.js");
}

config {
    type: "operations",
    hasOutput: true,
    name: "step_tbl_write_risk_score_fct",
    schema: dataform.projectConfig.vars.stagingDataset,
    dependencies: ["step_tbl_process_risk_score_fct"],
    description: "Loads processed risk score fact data into the target table.",
    tags: ["risk", "fact", "score"]
}

${fn_SCD2load({
    source_ref: ref("step_tbl_process_risk_score_fct"),
    target_name: target.target_table,
    project_id: projectConfig.projectName,
    tgt_dataset: datasets.target,
    hash_column: target.hash_dif,
    natural_key: target.bk[0],
    target_params: target
})}
