js {
  const glb_env = require("includes/glb_env.js");
  const { source } = require("definitions/param/source/ehr_event.js");
}

config {
    type: "table",
    schema: glb_env.datasets.staging,
    name: "step_tbl_read_wait_event_fct",
    description: "Getting the required data from dimensions and source tables.",
    tags: ["f_wait_time", "fct"]
}
WITH cte_read AS (
  SELECT 
    visit_id,
    event_id,
    doctor_id,
    event_sequence,
    patient_id,
    facility_code,
    department_code,
    ref_code,
    event_date,
    service_start_time,
    actual_start_time,
    end_time
  FROM `fy23-asc-addg-dataverse.b5_HIS.EHR_EVENT`
  WHERE event_type in( 'WAIT_EVENT','wait_time')
)

SELECT 
  visit_id,
  event_id,
  doctor_id,
  event_sequence,
  patient_id,
  facility_code,
  department_code,
  ref_code,
  event_date,
  service_start_time,
  actual_start_time,
  end_time
FROM cte_read