
js {
    const glb_env = require("includes/glb_env.js");
    const {
        source
    } = require("definitions/param/source/ehr_facility_dept_f.js");
}

config {
    type: "table",
    schema: glb_env.datasets.staging,
    name: "facility_dim_read",
    description: "Facility Details",
    tags: ["facility", "conformed", "dim"]
}

WITH
  raw_facility_department AS (
  -- Pulling all columns directly from the operational source table as is
  SELECT
    facility_code,
    dept_capacity,
    head_doctor_id,
    department_type,
    department_name,
    state,
    total_licensed_beds,
    zip_code,
    is_dept_active,
    facility_type_code,
    region,
    is_facility_active,
    facility_name,
    city,
    department_code,
    last_updated
  FROM
    ${ref(source.table_name)}
    -- This replaces DISTINCT and guarantees only ONE unique row per facility_code
  QUALIFY
    ROW_NUMBER() OVER(PARTITION BY facility_code ORDER BY last_updated DESC, is_facility_active DESC ) = 1 )
    -- Final pass extraction
SELECT
  dept_capacity,
  head_doctor_id,
  department_type,
  department_name,
  state,
  total_licensed_beds,
  zip_code,
  is_dept_active,
  facility_type_code,
  region,
  is_facility_active,
  facility_name,
  city,
  department_code,
  last_updated,
  facility_code
FROM
  raw_facility_department
